name: GemAI
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

#-------------Packages--------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.6.2
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  flutter_html: ^3.0.0
  camera: ^0.11.3+1
  image_picker: ^1.2.1
  syncfusion_flutter_pdfviewer: ^32.2.5

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.3
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.1.2

  # Firebase
  firebase_core: ^4.4.0

#--------------Packages End-------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_images/
    - assets/images/PopularGems/
    - assets/images/PopularGems/DetailsImages/
    - assets/images/user/
    - assets/images/books/
    - assets/images/RealFake/
    - assets/images/Articles/
    - assets/images/MarketPlace/
    - assets/images/animations/
    - assets/logos/
    - assets/pdfs/
    - assets/docs/terms_of_use.html
    - assets/docs/privacy_policy.html

  fonts:
    - family: TimesRomanFont
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/times-bd.ttf
          weight: 800
        - asset: assets/fonts/times-bi.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/times-i.ttf
          style: italic
