// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2duCg2aL4ZCVCSr8zRaZcI9WtrulpVhc',
    appId: '1:735650347383:android:f3b35cf3f910ae076fc972',
    messagingSenderId: '735650347383',
    projectId: 'gemai-cb042',
    storageBucket: 'gemai-cb042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmA1dJc5Auw4TmdWxxMoeANoDo2uVQb5U',
    appId: '1:735650347383:ios:7ab3d28a8136549d6fc972',
    messagingSenderId: '735650347383',
    projectId: 'gemai-cb042',
    storageBucket: 'gemai-cb042.firebasestorage.app',
    androidClientId: '735650347383-7u5k3bf3klgbooafpgsib2u3u9nkuvi3.apps.googleusercontent.com',
    iosClientId: '735650347383-4rlvfhdm4buki11hbj68c2regaq5j9ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemai',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzuTlp6L8WpllXxWtTAhhT-S2D-znTN2M',
    appId: '1:735650347383:web:a7b8386b688bc7bf6fc972',
    messagingSenderId: '735650347383',
    projectId: 'gemai-cb042',
    authDomain: 'gemai-cb042.firebaseapp.com',
    storageBucket: 'gemai-cb042.firebasestorage.app',
  );

}